# Put domain configuration in this file
# See http://seedstack.org/docs/seed/configuration for more information about configuration

# Class configuration is often needed for domain modules
# See http://seedstack.org/docs/seed/configuration/#class-configuration for more information
classes:
