{% if docker.enabled %}
version: "2"
services:
{% if persistence.enabled %}
  db:
{% if persistence.type == "jpaHibernate" %}
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
{% elseif persistence.type == "mongo" %}
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
{% endif %}
{% endif %}
  app:
    image: {{ project.groupId }}/{{ project.artifactId }}

{% if persistence.enabled %}
    links:
      - db
{% endif %}
    ports:
      - 8080:8080
{% if persistence.enabled %}
    environment:
{% if persistence.type == "jpaHibernate" %}
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}
{% elseif persistence.type == "mongo" %}
      DB_URL: mongodb://db:27017/${DB_NAME}
{% endif %}
{% endif %}
{% endif %}
